name: Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  rust_tests:
    name: Rust Checks
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
          override: true
          profile: minimal
      - name: Install Protoc with apt
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          protoc --version  # Verify installation

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-rust-tests-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            cargo-${{ runner.os }}-rust-tests-
            cargo-${{ runner.os }}-

      - name: Check formatting
        run: cargo fmt --check

      - name: Check clippy
        run: cargo clippy

      - name: Run tests
        run: cargo test -- --test-threads=1 # todo fix it so we can run tests in parallel
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
